# Generated by Django 5.1.1 on 2024-09-29 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='new.basemodel')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('twitter', models.TextField()),
                ('facebook', models.TextField()),
                ('linkedin', models.TextField()),
                ('instagram', models.TextField()),
                ('youtube', models.TextField()),
                ('telegram', models.TextField()),
            ],
            bases=('new.basemodel',),
        ),
        migrations.CreateModel(
            name='AdsModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='new.basemodel')),
                ('image', models.ImageField(upload_to='ads_images/')),
                ('links', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('one', 'ONE')], max_length=5)),
            ],
            bases=('new.basemodel',),
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='new.basemodel')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            bases=('new.basemodel',),
        ),
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='new.basemodel')),
                ('full_name', models.CharField(max_length=50)),
                ('your_email', models.EmailField(max_length=254)),
                ('your_number', models.CharField(max_length=13)),
                ('message', models.TextField()),
            ],
            bases=('new.basemodel',),
        ),
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='new.basemodel')),
                ('name', models.CharField(max_length=200)),
            ],
            bases=('new.basemodel',),
        ),
        migrations.CreateModel(
            name='NewModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='new.basemodel')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='new_images/')),
                ('description', models.TextField()),
                ('body', models.TextField()),
                ('views', models.IntegerField(default=0)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_new', to='new.categorymodel')),
                ('tags', models.ManyToManyField(blank=True, to='new.tagmodel')),
            ],
            bases=('new.basemodel',),
        ),
    ]
