# Generated by Django 5.1.1 on 2024-10-04 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0003_newmodel_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagmodel',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
